stakater/application

- README.md
- application/templates/service.yaml
- application/templates/servicemonitor.yaml
- application/values.yaml
Don't need unnecessary labels. use already defined label `app`
> remove unnecessary labels and other doc fix

- README.md
- application/templates/_helpers.tpl
- application/templates/deployment.yaml
- application/templates/service.yaml
- application/values.yaml
This PR
- removes default values for rolling update as cant set strategy to recreate due to it
- changes pod label as application label is part of chart now
- adds values for mount pvc and path in case persistence is true
> Add volume mounts persistence and fix labels

- README.md
- application/templates/endpointmonitor.yaml
So, additional config shld present this part
```
uptimeRobotConfig:
alertContacts: "6786045_0_0"
```
in
```
apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
name: sonarqube
namespace: cluster-enento-devtest
spec:
forceHtpps: true
url: https://sonarqube-openshift-stakater-sonarqube.apps.devtest.adx45rg.kube.cloud/
uptimeRobotConfig:
alertContacts: "6786045_0_0"
```
> add additional config for endpoint monitor

- README.md
- application/templates/deployment.yaml
Fixes the templating for Deployment.envFrom.secretRef
Fixes the error `error converting YAML to JSON: yaml` [...] `did not find expected key`
> Fix typo in Deployment templating

- .github/workflows/push.yaml
Updated generate tag version from 1.26.0 to 1.36.0 due security vulnerability
> Update generate tag version to 1.36.0

- README.md
- application/templates/deployment.yaml
- application/values-test.yaml
- application/values.yaml
This probe is good for slow starting applications instead of relying om initialDelaySeconds that will make the pod start slower then necessar.
Docs: 
StartupProbe indicates that the Pod has successfully initialized. If specified, no other probes are executed until this completes successfully. If this probe fails, the Pod will be restarted, just as if the livenessProbe failed. This can be used to provide different probe parameters at the beginning of a Pod's lifecycle, when it might take a long time to load data or warm a cache, than during steady-state operation. This cannot be updated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
> Add support for Deployment startup probe

- README.md
- application/templates/deployment.yaml
- application/values-test.yaml
- application/values.yaml
Added support for defining Security Context at Container level for deployments.
**Example**:
deployment:
containerSecurityContext:
runAsNonRoot: false
**Note: By default runAsNonRoot and readOnlyRootSystem is true.**
> Support for defining SC at container level

- CHANGELOG.md
- application/values.yaml
Comment Deployment Probes.  liveness probe in default values is overriding liveness probe in values outside because values from default are merged with values from outside causing both tcpSocket and httpGet to be present, chart gives precendence to exec over httpGet over tcpSocket, this is causing the pod to be stuck in a crashback loop because probe will be different for every pod
> Disable Deployment Probes

- Tiltfile
- Tiltfile-delete
- application/templates/_helpers.tpl
- application/templates/alertmanagerconfig.yaml
- application/templates/certificate.yaml
- application/templates/configmap.yaml
- application/templates/cronjob.yaml
- application/templates/deployment.yaml
- application/templates/endpointmonitor.yaml
- application/templates/externalsecrets.yaml
- application/templates/forecastle.yaml
- application/templates/grafanadashboard.yaml
- application/templates/hpa.yaml
- application/templates/ingress.yaml
- application/templates/networkpolicy.yaml
- application/templates/pdb.yaml
- application/templates/prometheusrule.yaml
- application/templates/pvc.yaml
- application/templates/role.yaml
- application/templates/rolebinding.yaml
- application/templates/route.yaml
- application/templates/sealedsecrets.yaml
- application/templates/secret.yaml
- application/templates/secretproviderclass.yaml
- application/templates/service.yaml
- application/templates/serviceaccount.yaml
- application/templates/servicemonitor.yaml
- application/values-test.yaml
- application/values.yaml
- improve enable conditions
- user _helpers.tpl properly
- move to common k8s labels and remove other labels
And fixes following:
> improve enable conditions and use helpers.tpl

- CHANGELOG.md
- README.md
- application/templates/ingress.yaml
- application/values-test.yaml
`paths` key in ingress manifest is misplaced
> fix: Repair ingress multiple paths definitions

- CHANGELOG.md
- application/templates/cronjob.yaml
- application/templates/hpa.yaml
* Cronjob v1beta1 => v1
* HorizontalPodAutoscaler v2beta2 => v2
see https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25
> migrate cronjob and hpa to new api versions

- CHANGELOG.md
Add missing entries to CHANGELOG.md
> chore: Add missing entries to CHANGELOG.md

- .github/workflows/pull_request.yaml
Changes the actions workflow to run unit tests from the PR head.
Fixes #250.
> fix: run unit tests from the pr head

- CHANGELOG.md
- README.md
- application/templates/_helpers.tpl
- application/templates/cronjob.yaml
- application/templates/deployment.yaml
- application/tests/cronjob_test.yaml
- application/tests/deployment_test.yaml
- application/values.yaml
Hi,
i really like the idea of creating a generic chart which can be used for many use cases, but i have a small issue with the Chart.
Currently you use the the following code block for the image definition:
```
{{- if .Values.deployment.image.digest }}
image: "{{ .Values.deployment.image.repository }}@{{ .Values.deployment.image.digest }}"
{{- else if .Values.deployment.image.tag }}
image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
{{- end }}
```
This means that currently `deployment.image.tag` is a required param. The current default value is `v1.0.0`. This is a bit odd, because a image definition is also valid w/o a tag. For example, the following definitions are also valid and not all of them are currently supported by the chart:
``` …
```
> make deployment.image.tag and job.image.tag optional

- CHANGELOG.md
- README.md
- Tiltfile
- Tiltfile-delete
- application/templates/vpa.yaml
- application/values-test.yaml
- application/values.yaml
Fixes https://github.com/stakater/application/issues/32
> feat: Add vertical pod autoscaler template

- CHANGELOG.md
- Tiltfile
- application/templates/ingress.yaml
- application/values-test.yaml
- application/values.yaml
This reverts PR https://github.com/stakater/application/pull/240.
> Revert "Defining default path spec in ingress if hosts.*.paths is null"

- CHANGELOG.md
- README.md
- application/templates/cronjob.yaml
This PR adds support for the following properties in CronJob:
- `.spec.jobTemplate.spec.activeDeadlineSeconds`
- `.spec.jobTemplate.spec.backoffLimit`
- `.spec.jobTemplate.spec.template.metadata.annotations`
- `.spec.jobTemplate.spec.template.metadata.labels`
- `.spec.jobTemplate.spec.template.spec.topologySpreadConstraints`
- `.spec.jobTemplate.spec.template.spec.securityContext`
> feat(cronjob): Add more properties

- CHANGELOG.md
- application/templates/_helpers.tpl
- application/templates/alertmanagerconfig.yaml
- application/templates/certificate.yaml
- application/templates/configmap.yaml
- application/templates/cronjob.yaml
- application/templates/deployment.yaml
- application/templates/endpointmonitor.yaml
- application/templates/externalsecrets.yaml
- application/templates/forecastle.yaml
- application/templates/grafanadashboard.yaml
- application/templates/hpa.yaml
- application/templates/ingress.yaml
- application/templates/networkpolicy.yaml
- application/templates/pdb.yaml
- application/templates/prometheusrule.yaml
- application/templates/pvc.yaml
- application/templates/role.yaml
- application/templates/rolebinding.yaml
- application/templates/route.yaml
- application/templates/sealedsecrets.yaml
- application/templates/secret.yaml
- application/templates/secretproviderclass.yaml
- application/templates/service.yaml
- application/templates/serviceaccount.yaml
- application/templates/servicemonitor.yaml
- application/templates/vpa.yaml
The cronjob template misses a `---` new document separation. This means all cronjobs are scrambled together and only a frankenstein version of all of them is emitted. 
This PR also does some lint:
- move the new document separator to the beginning of templates
- add empty newline at the end of files
- remove empty newlines in the middle of files
- move helpers to _helpers file.
> fix: allow multiple cronjobs

- application/templates/cronjob.yaml
Currently cronjob was getting created regardless of Values.rabc.enabled is set to true or false.  Added changed so that if rbac is enabled then only serviceAccount field will get applied for cronjob
> Fixed cronjob template - serviceAccountName was getting applied even if it is disabled from values.

- application/templates/vpa.yaml
- application/values.yaml
Support for vpa.updatePolicy.updateMode=Auto|Recreate|Initial|Off (default is Auto)
```
$ helm template application --set=vpa.enabled='true' --validate | grep -A1 updatePolicy
updatePolicy:
updateMode: Auto
```
also works for other updatePolicy settings
```
$ helm template application --set=vpa.enabled='true' \
--set=vpa.updatePolicy.updateMode=Off \
--set=vpa.updatePolicy.minReplicas=3 --validate | grep -A2 updatePolicy
updatePolicy:
minReplicas: 3
updateMode: "Off"
```
Link to CRD for reference: https://github.com/kubernetes/autoscaler/blob/vertical-pod-autoscaler-1.0.0/vertical-pod-autoscaler/deploy/vpa-v1-crd-gen.yaml#L377
> Allow configuration of vpa.updatePolicy

- application/templates/secret.yaml
The secret data is empty until I use dollar sign.
Here's my values.yaml example that doesn't work as expected
```
secret:
enabled: true
files:
credentials:
SECRET: <my_secret>
```
> Fix bug with secrets being empty

- application/templates/deployment.yaml
- application/tests/deployment_test.yaml
- application/values.yaml
Add grpc probing to this Helm Chart.
To allow developers to add probing to their grpc applications. 
https://kubernetes.io/blog/2022/05/13/grpc-probes-now-in-beta/
By adding the option of configuring a grpc deployment probing in this Helm Chart.
> Add grpc probe to deployment

- CHANGELOG.md
- README.md
- application/templates/job.yaml
- application/tests/job_test.yaml
- application/values-test.yaml
- application/values.yaml
Hey folks.
Thank you very much for maintaining this awesome chart!
This PR introduces the possibility of adding Jobs as part of the deployments.
The use case for this is quite simply to be able to utilize helm hooks for deployments (ie. for database migrations).
Currently, the implementation is very generic and could be used for any kind of purpose alongside the deployment (or CronJob). There is an alternative solution to this that I would also consider (and am happy to provide): Instead of making it very generic (and therefore flexible) we could add a "initJob" config tree to the deployment itself that would come preconfigured. There we would mirror the deployment configuration and behavior (env and such) to make it very simple to execute a helm hook.
Let me know what you think!
> Adds Jobs feature to the chart.

- .github/workflows/pull_request.yaml
It passes down global envs to downstream docker runs https://github.com/aslafy-z/test-action/actions/runs/9908946364/job/27375873789
> ci: allow checkov to use kubeconfig

- README.md
- application/templates/cronjob.yaml
- application/templates/deployment.yaml
- application/values-test.yaml
- application/values.yaml
add priorityclassname and lifecycle
> feat: add priorityclassname and lifecycle

- .github/workflows/pull_request.yaml
helm-unittest team released https://github.com/helm-unittest/helm-unittest/releases/tag/v0.5.2-test2 which breaks `helm plugin install https://github.com/helm-unittest/helm-unittest` (latest version).
Specifying `v0.5.x` takes the latest non-prerelease tag.
> ci: pin helm-unittest version

- .github/workflows/pull_request.yaml
- .pre-commit-config.yaml
- Makefile
- README.md
- README.md.gotmpl
- application/templates/alertmanagerconfig.yaml
- application/templates/backup.yaml
- application/templates/certificate.yaml
- application/templates/deployment.yaml
- application/templates/endpointmonitor.yaml
- application/templates/externalsecrets.yaml
- application/templates/forecastle.yaml
- application/templates/hpa.yaml
- application/templates/ingress.yaml
- application/templates/networkpolicy.yaml
- application/templates/pdb.yaml
- application/templates/prometheusrule.yaml
- application/templates/pvc.yaml
- application/templates/route.yaml
- application/templates/service.yaml
- application/templates/serviceaccount.yaml
- application/templates/servicemonitor.yaml
- application/templates/vpa.yaml
- application/tests/deployment_test.yaml
- application/values.yaml
Preview at https://github.com/stakater/application/blob/feat/generated-readme/README.md
- Generate README.md with https://github.com/norwoodj/helm-docs
- Add pre-commit hook and GitHub Action run to validate README
- Document the whole values file
- Move some defaults from templates to values
- Set `certificate.issuerRef.group` to `cert-manager.io`
Thanks to https://github.com/norwoodj/helm-docs/pull/260, we will soon be able to render a bit better some of the default values.
Fixes #242
> feat: generated Helm documentation

- README.md
- application/templates/deployment.yaml
- application/values-test.yaml
- application/values.yaml
This chart supports only one image pull secret instead of a list for the deployment.yml manifest. This Pull Request aims at supporting a list of secrets.
> feat(deployment): support list of imagePullSecrets #major

- application/templates/cronjob.yaml
Corrected the indentation level of securityContext to instead apply it to each container within the jobs.
> feat(cronjob): Corrected indentation of securityContext container params #minor

- README.md
- application/templates/cronjob.yaml
- application/templates/deployment.yaml
- application/templates/job.yaml
- application/values-test.yaml
- application/values.yaml
Fixes #365 
If wanted, I can also add it to job and cronjob but perhaps then support for dnsConfig should be added there as well?
> feat: add dnsPolicy support to Deployment

- README.md
- application/values.yaml
RollingUpdate is an optional property only used when we set the strategy type as "RollingUpdate". If we set the type as "Recreate", this property breaks the deployments wit the following message:
Deployment.apps "<app>" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
It gets more problematic when we use stakater/apps Helm Chart as a subchart for our applications. Helm has a known bug that doesn't allow override values from the subchart. So, if we need to deploy an application with the Recreate strategy, it is not possible as the deployment will always break with the error mentioned above.
The simpler solution is to comment the "rollingUpdate" property to prevent the Recreate deployments to break when using a subchart.
> fix: Remove default values for rollingUpdate

- README.md
- application/values.yaml
Making `certificate.commonName` default to null. It should not default to `admin-app` as this field is optional. It can be set according to specific needs but it should not default to an irrelevant value. 
https://cert-manager.io/docs/usage/certificate/#:~:text=%23%20Avoid%20using%20commonName,%3A%20example.com
The main reason for making this change is that whenever we try to create `Certificate`, its `commonName` field defaults to `admin-app` which is unexpected behavior in default scenario. Setting it to `nil` will make more sense.
> feat: make cert manager certificate's commonName optional #major

- application/templates/deployment.yaml
- application/templates/job.yaml
Remove extra newlines in deployment and job manifests that leaks to rendered manifests.
> fix: remove newlines in rendered manifests

- application/templates/service.yaml
Hi, 
I try your generic chart, and I need to customize labels of deployment with deployment.podLabels.
This works fine for deployment, as it only adds the label to spec.template.metadata.labels (example deployTimestamp label), not to spec.selector.matchLabels.
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: api-1
spec:
selector:
matchLabels:
app.kubernetes.io/name: api-1
template:
metadata:
labels:
app.kubernetes.io/name: api-1
deployTimestamp: '1751286504'
```
However, this is also added to the selector on the service. During a rolling update, the service is updated with a changing label and can no longer reach the old pods, so there's a 503 error until at least one new pod is launched.
I think it's better to stay consistent with the deployment's spec.selector.matchLabels
``` …
```
> fix(service): remove podLabels from Service selector

- application/templates/backup.yaml
The includedNamespaces key was previously placed inside the range
loop, which caused two issues:
- If .Values.backup.includedNamespaces was nil, Helm errored
- If multiple namespaces were set, the key was repeated for each
item, producing invalid YAML
This change moves includedNamespaces outside the loop and adds a
kindIs "invalid" guard. This prevents errors on nil and renders a
valid list when multiple namespaces are provided.
> fix(backup): move includedNamespaces out of range and guard for nil
