- README.md
- application/templates/endpointmonitor.yaml
- application/values.yaml
> Add endpoint moinitor

- application/templates/endpointmonitor.yaml
> fix the broken endpointMonitor

- README.md
- application/templates/deployment.yaml
- application/values.yaml
> Add support for optional ports in deployment

- application/templates/certificate.yaml
- application/values.yaml
> Add templated values in values.yaml for cert subject

- application/templates/certificate.yaml
- application/values.yaml
> Remove duplicate yaml templating from cert subject

- README.md
- application/templates/deployment.yaml
- application/values.yaml
> Allow to append namesuffix to envFrom for configmap and secret

- application/templates/sealedsecrets.yaml
> Fix issue while generating multiple sealed-secrets

- README.md
- application/templates/deployment.yaml
- application/values.yaml
Added support for hostAliases to make it possible to add entries to a pods /etc/hosts file
> Added deployment.hostAliases

- README.md
- application/values.yaml
> Add host for route in values.yaml

- .github/workflows/pull_request.yaml
- .github/workflows/push.yaml
- application/templates/ingress.yaml
- application/values-test.yaml
Fix `push` and `pull_request` actions. Changes
- `helm install ${CHART_NAME} ${CHART_NAME} `**`-f ${CHART_NAME}/values-test.yaml`**` --dry-run --debug`
Fix ingress template:
-  There is no `serviceName` and `servicePort`, but `service.name` and `service.port.name/number`
- Annotations in `values-test.yaml` should have values as strings, even for booleans, eg. `true` should be `"true"`
> fix actions

- application/templates/endpointmonitor.yaml
> Fix endpointmonitor spec error when route and ingress are disabled

- application/values.yaml
improve readability of the values file
> improve readability

- README.md
- application/templates/deployment.yaml
- application/values.yaml
> Update replica field

- README.md
route.path was out of alignment in preview. fixed it.
> minor alignment fix | Updated README.md

- README.md
- application/templates/_helpers.tpl
> Change label chart

- README.md
- application/templates/ingress.yaml
- application/values-test.yaml
- application/values.yaml
this PR will add ingressClassName in the ingress chart
> Add ingressClassName in ingress chart

- application/values.yaml
This is a bogus commit to run push pipeline.
Details:
A new pull request was merged. A github action push workflow was running already that failed because of remote changes. The chart.yaml wasnt updated and new release wasnt created. This bogus commit is to trigger  github action push workflow so chart.yaml is updated and a new release could be created.
Failed Workflow: https://github.com/stakater-charts/application/actions/runs/2306244448
Pull Request: https://github.com/stakater-charts/application/pull/173
> Bogus commit to run push pipeline

- application/values.yaml
This is a bogus commit to run push pipeline.
**Details:**
A new pull request was merged. A github action push workflow was running already that failed because of remote changes. The chart.yaml wasnt updated and new release wasnt created. This bogus commit is to trigger github action push workflow so chart.yaml is updated and a new release could be created.
Failed Workflow: https://github.com/stakater-charts/application/actions/runs/2306244448
Pull Request: https://github.com/stakater-charts/application/pull/173
**( Note: Previous Bogus commit didnt work as expected because there was a commit with #none after the last time a tag was generated that didnt bump the chart version and no release was made. )**
> Bogus commit to run push pipeline 2

- .github/workflows/push.yaml
Change gh-action-push to repush in case of failure, it repull from remote and pushes again.
> Change gh-action-push to repush in case of failure

- README.md
- application/templates/service.yaml
- application/values-test.yaml
- application/values.yaml
add type in the service template
> [add-type-in-service]

- README.md
> clarify the kind of applications

- README.md
> fix indentation issues in the readme

- README.md
> clarify version number change

- README.md
- application/Chart.yaml
- application/templates/cronjob.yaml
- application/templates/deployment.yaml
- application/values.yaml
Add an optional image.digest field to Deployment and CronJob resources.
> feat: add image.digest value to deployment and cronjob

- README.md
- application/templates/pdb.yaml
Optionally upgrade PDB to v1 if supported by the target cluster.
> feat: upgrade pdb to v1

- README.md
I bumped the minor instead of the patch in #200
> fix: update changelog

- CHANGELOG.md
- application/templates/externalsecrets.yaml
- application/values-test.yaml
- application/values.yaml
Update externalsecret apiversion from v1alpha1 to v1beta1 as v1alpha1 is deprecated
> Update externalsecret apiversion from v1alpha1 to v1beta1 #minor

- CHANGELOG.md
- application/templates/externalsecrets.yaml
- application/values-test.yaml
- application/values.yaml
Reverts stakater/application#210
> [skip-ci] Revert "Update externalsecret apiversion from v1alpha1 to v1beta1 #minor"

- CHANGELOG.md
- README.md
- application/templates/deployment.yaml
- application/templates/service.yaml
- application/values.yaml
> added template for oauth proxy deployment to use http container port in case of ingress

- .github/workflows/pull_request.yaml
- .github/workflows/push.yaml
- LICENSE
- README.md
> add mit license

- CHANGELOG.md
- application/templates/service.yaml
- application/values.yaml
> feat: allow overriding clusterIP

- CHANGELOG.md
- application/templates/deployment.yaml
This PR allows to request additional or non standard resources.
Also allows unsettings default resources from values using `null`.
> fix: allow setting arbitrary resource constraints

- CHANGELOG.md
- application/templates/deployment.yaml
- application/tests/deployment_test.yaml
- application/values-test.yaml
don't add service account until user asks for it! it will get default service account
Fixes https://github.com/stakater/application/issues/195
> fix: optional service account

- README.md
- application/templates/deployment.yaml
- application/values-test.yaml
- application/values.yaml
I'm lacking terminationGracePeriodSeconds value
So here's my solution
> Add terminationGracePeriodSeconds

- application/templates/hpa.yaml
Adding the ability to set autoscaling behavior as per https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior
> Allowing HPA behavior to be set

- CHANGELOG.md
- application/templates/service.yaml
> fix clusterIP null field

- CHANGELOG.md
- README.md
- application/templates/grafanadashboard.yaml
- application/values-test.yaml
- application/values.yaml
This PR updates the api version for grafana dashboard and add new fields to it
> Update grafana dashboard #major

- README.md
- application/templates/cronjob.yaml
checkout https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/\#time-zones for more info
Signed-off-by: Muhammed Hussein Karimi <info@karimi.dev>
> ✨ feat: timeZone option added to cronJob

- CHANGELOG.md
- application/templates/backup.yaml
Add option for defaultbackupdefaultVolumesToRestic
It is set to true by default
> Add option for defaultbackupdefaultVolumesToRestic

- .github/workflows/pull_request.yaml
- Interpolate CHART_NAME env variable before passing inputs to action.
- Disable checkov action soft_fail
- Make checkov run in a live cluster (Helm pulls APIVersions from it)
> fix(ci): repair checkov

- application/templates/deployment.yaml
I apologize, but during the review process of the [previous pr](https://github.com/stakater/application/pull/313) when I was making changes as requested, an error was made that ended up in the master branch. Please merge to fix it.
@d3adb5  @aslafy-z @rasheedamir
> fix: deployment priorityclassname

- application/templates/ingress.yaml
- application/values-test.yaml
- application/values.yaml
Remove unused fields 
- `ingress.pathType`
- `ingress.servicePort`
> fix(ingress): remove unused fields

- application/templates/backup.yaml
- application/values.yaml
> tenant namespaces can be added in includeNamespace while the default backup namespace would be the -system namespace

- application/templates/backup.yaml
- application/tests/backup_test.yaml
- application/values.yaml
Followup https://github.com/stakater/application/pull/355. 
- Correctly add field to docs
- Allow multiple namespaces
- Add templating to the field
- Add tests
> feat(backups): improve includedNamespaces and add docs

- application/templates/cronjob.yaml
- application/templates/job.yaml
- application/tests/cronjob_test.yaml
- application/tests/job_test.yaml
> fix(*job): render labels and annotations as a map

- .github/workflows/release.yaml
Relates to https://github.com/stakater/application/issues/241
> ci: generate release with automatic changelog

- README.md
- application/Chart.yaml
- application/values.yaml
Closes https://github.com/stakater/application/issues/236
> feat(deployment): remove resources defaults

- README.md
- application/templates/deployment.yaml
- application/values.yaml
Fixes https://github.com/stakater/application/issues/452
> feat(deployment): add runtimeClassName support to deployment
